version: '2.1'
networks:
  connectionworkers-network:
services:
    sql-server-db:
        container_name: sql-server-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        networks:
            - connectionworkers-network
        ports: 
            - "1433:1433"
        environment: 
            SA_PASSWORD: "FJEWT4ER_tay582"
            ACCEPT_EULA: "Y"    